tap "homebrew/core"
tap "homebrew/bundle"
tap "AlexanderWillner/tap"
brew "ack"
brew "fzf"
brew "jq"
brew "ripgrep"
brew "terminal-notifier"
brew "tmux", args: ["HEAD"]
brew "yarn"
brew "trash"
brew "mas"
brew "htop"
brew "nnn"
mas "1Password 7", id: 1333542190
